import { UserProfile, Badge } from '@/types';

export const mockUser: UserProfile = {
  id: '1',
  name: 'Alex Rivera',
  username: 'alexdev',
  profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  grade: 'College 2nd Year',
  course: 'BS Computer Science',
  age: 19,
  hobbies: ['Gaming', 'Programming', 'Reading', 'Music'],
  expertise: ['JavaScript', 'React', 'TypeScript', 'Node.js'],
  status: 'mentee',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const mockCandidates: UserProfile[] = [
  {
    id: '2',
    name: 'Sarah Chen',
    username: 'sarahcodes',
    profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    grade: 'College 3rd Year',
    course: 'BS Computer Science',
    age: 20,
    hobbies: ['Programming', 'Photography', 'Gaming'],
    expertise: ['JavaScript', 'React', 'Python', 'AWS'],
    status: 'mentor',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Michael Torres',
    username: 'miketech',
    profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    grade: 'College 4th Year',
    course: 'BS Information Technology',
    age: 21,
    hobbies: ['Coding', 'Music', 'Gaming', 'Reading'],
    expertise: ['TypeScript', 'Node.js', 'MongoDB', 'Docker'],
    status: 'mentor',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Emma Johnson',
    username: 'emmaj',
    profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    grade: 'College 2nd Year',
    course: 'BS Computer Engineering',
    age: 19,
    hobbies: ['Reading', 'Art', 'Programming'],
    expertise: ['C++', 'Python', 'Arduino', 'IoT'],
    status: 'mentor',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'David Kim',
    username: 'davidk',
    profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    grade: 'College 3rd Year',
    course: 'BS Computer Science',
    age: 20,
    hobbies: ['Gaming', 'Music Production', 'Programming'],
    expertise: ['JavaScript', 'React', 'Vue.js', 'Firebase'],
    status: 'mentor',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockBadges: Badge[] = [
  {
    id: 'badge-1',
    name: 'Profile Complete',
    description: 'Complete your profile with all information',
    icon: '✅',
    category: 'profile',
    unlocked: true,
    unlockedAt: new Date().toISOString(),
    progress: 100,
    maxProgress: 100,
  },
  {
    id: 'badge-2',
    name: 'First Connection',
    description: 'Make your first mentorship connection',
    icon: '🤝',
    category: 'mentorship',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'badge-3',
    name: 'Skill Master',
    description: 'Master 5 different skills',
    icon: '🎯',
    category: 'skills',
    unlocked: false,
    progress: 4,
    maxProgress: 5,
  },
  {
    id: 'badge-4',
    name: '10 Hour Streak',
    description: 'Participate in 10 hours of mentorship',
    icon: '⏰',
    category: 'activity',
    unlocked: false,
    progress: 6,
    maxProgress: 10,
  },
  {
    id: 'badge-5',
    name: '5 Star Mentor',
    description: 'Receive 5 five-star reviews',
    icon: '⭐',
    category: 'reviews',
    unlocked: false,
    progress: 2,
    maxProgress: 5,
  },
  {
    id: 'badge-6',
    name: 'Early Adopter',
    description: 'Join StudyQuest in the first month',
    icon: '🚀',
    category: 'profile',
    unlocked: true,
    unlockedAt: new Date().toISOString(),
    progress: 1,
    maxProgress: 1,
  },
];
